create database QLKS_QLDA
go
use QLKS_QLDA

CREATE TABLE NHANVIEN (
    MaNV VARCHAR(10) PRIMARY KEY,
    HoNV NVARCHAR(50) NOT NULL,
    TenNV NVARCHAR(50) NOT NULL,
    NgaySinh DATE NOT NULL,
    DiaChi NVARCHAR(255) NOT NULL,
    SDT VARCHAR(15) NOT NULL,
    ChucVu NVARCHAR(50) NOT NULL
);

CREATE TABLE KHACHHANG (
	MaKH VARCHAR(10) PRIMARY KEY,
	HoKH NVARCHAR(50) NOT NULL,
	TenKH NVARCHAR(50) NOT NULL,
	CMND VARCHAR(20) NOT NULL,
	Sdt VARCHAR(20) NOT NULL,
)

CREATE TABLE LOAIPHONG (
	MaLoaiPhong VARCHAR(10) PRIMARY KEY,
	LoaiPhong NVARCHAR(50) NOT NULL,
	Gia INT NOT NULL,
	Anh NVARCHAR(50) NOT NULL,
)

CREATE TABLE TANG (
	MaTang VARCHAR(10) PRIMARY KEY,
	Tang INT,
	Anh NVARCHAR(50) NOT NULL,
)

CREATE TABLE PHONG (
	MaPhong VARCHAR(10) PRIMARY KEY,
	MaLoaiPhong VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES LOAIPHONG(MaLoaiPhong),
	MaTang VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES TANG(MaTang),
)

CREATE TABLE DICHVU (
	MaDV VARCHAR(10) PRIMARY KEY,
	TenDV NVARCHAR(50) NOT NULL,
	Gia INT NOT NULL,
	TonKho INT NOT NULL,
	DonVi NVARCHAR(50) NOT NULL,
	Anh NVARCHAR(50) NOT NULL,
)

CREATE TABLE PHIEUDAT (
    MaKH VARCHAR(10) PRIMARY KEY,
    NgayDat DATE NOT NULL,
    NgayVao DATE NOT NULL,
    NgayRa DATE NOT NULL,
    SoPhong INT NOT NULL,
    TinhTrang NVARCHAR(50) NOT NULL
);

CREATE TABLE GOIDV (
	MaGoiDV VARCHAR(10) PRIMARY KEY,
	MaPhong VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES PHONG(MaPhong),
	MaLoaiPhong VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES LOAIPHONG(MaLoaiPhong),
	MaTang VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES TANG(MaTang),
    NgayVao DATE NOT NULL,
	TinhTrang NVARCHAR(20) NOT NULL
)
