//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormThongTinNhanVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DICHVU
    {
        public string MaDV { get; set; }
        public string TenDV { get; set; }
        public int Gia { get; set; }
        public int TonKho { get; set; }
        public string DonVi { get; set; }
        public string Anh { get; set; }
    }
}
